### ISSUE TITLE
deerma.humidifier.jsq - water level

### ISSUE THREAD

**Issue by Magix3D** [artem-sedykh/mini-humidifier#65]
Hey Artem,
I got the tip to write you directly, so here goes nothing.
I think the easiest way is to link the [ha-post ](https://community.home-assistant.io/t/xiaomi-humidifier-support/35672/170) and to ask you to read the last few posts.
In conculsion - the water level of the on the title mentioned humidifier isn't shown, it always shows 0.
Looking forward to your answer.
Regards

**Comment by artem-sedykh** [comment]
Good day! your humidifier does not have a water level.  
https://www.home-assistant.io/integrations/xiaomi_miio/#air-humidifier-jsqjsq1mjjsq-deermahumidifierjsqdeermahumidifierjsq1deermahumidifiermjjsq  
You can add all the humidifier related entities so that I can add it  
for example  

![image](https://user-images.githubusercontent.com/861063/132135207-c939ead3-0292-48e8-a830-6c6c73fecfe0.png)
![image](https://user-images.githubusercontent.com/861063/132135221-0ddc99d2-9d09-4fb4-a976-1d322e67bd53.png)
and others
