### ISSUE TITLE
the card does not display

### ISSUE THREAD

**Issue by shurakenas** [artem-sedykh/mini-humidifier#83]
type: custom:mini-humidifier
entity: fan.xiaomi_air_humidifier
model: deerma.humidifier.jsq

**Comment by regevbr** [comment]
Without more information it will be impossible to help... Please provide versions of ha and the plugin, a screen shot and any errors shown in the browser console.

**Comment by regevbr** [comment]
Thanks. So the card does display... it is not empty :-) 

This card is highly customizable and it is very verbose to do it :-) In order to make life easier, the maintainer created a preset of configurations that can be used more easily.

When you set a model, you actually choose to fill the configuration with a premade ad-hoc configuration. You can control the same configuration entirely on your own, without the need of the model if you choose to, in case it doesn't work for you, or just override certain parts of it.

In your case, the model you loaded uses the indicators configuration as shown here:

https://github.com/artem-sedykh/mini-humidifier/blob/9e40d0b9247a5b1915136e92ce7f21f0ad75692c/src/configurations/xiaomi_miio/deerma_humidifier_jsq.js#L28-L61

All it does is look at certain attributes of your defined entity and other entities based on it (like `sensor.{entity_id}_temperature`). If that entity doesn't have those attributes or the expected entities do not exist, then the behavior you are experiencing is as expected. If you know where to get those values from, just create the indicators config yourself to override it (again, refer to the readme on how to do that).

Please let me know if that addresses your issues :-)

**Comment by shurakenas** [comment]
Thanks. My experience will not be enough to write the configuration on my own.

**Comment by regevbr** [comment]
Sorry that I can't be of any more assistance. Once you gain some experience with HA and writing up yaml files, you can use the file I mentioned as a template and adjust it to your needs
